language: objective-c
osx_image: xcode10.2
before_script: "./scripts/add-keys.sh"
after_script: "./scripts/remove-key.sh"
script:
#  - "./scripts/swiftLint.sh"
  - bash ./scripts/buildPrebidMobile.sh || travis_terminate 1;
  - bash ./scripts/testPrebidMobile.sh || travis_terminate 1;
